name: deploy-py-lambda
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Python pip
      run: pip install --upgrade pip
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: kohrongying/py-lambda-action@v1.0.2
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-1:637423526753:lambda_layer_publish'
        lambda_function_name: 'fiap-tech-challenge-users-lambda'
        # exclude_files: 'tests my-other-file.txt'
        lambda_layer_publish: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        
